/*.woff
    Access-Control-Allow-Origin: *
    Content-Type: application/font-woff

/*.ttf
    Access-Control-Allow-Origin: *
    Content-Type: application/font-ttf

/*.eot
    Access-Control-Allow-Origin: *
    Content-Type: application/font-eot